<a href="https://colab.research.google.com/github/dha3sh/LetsUpgrade-Python-Data-Science-assignments/blob/main/np_sort_3d_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

a = np.array([[5, 14], [10, 1]])
arr1 = np.sort(a, axis = 0)		
print ("Along first axis : \n", arr1)		



a = np.array([[10, 14], [5, 1]])
arr2 = np.sort(a, axis = -1)		
print ("\nAlong first axis : \n", arr2)


a = np.array([[5, 14], [10, 1]])
arr1 = np.sort(a, axis = None)		
print ("\nAlong none axis : \n", arr1)


Along first axis : 
 [[ 5  1]
 [10 14]]

Along first axis : 
 [[10 14]
 [ 1  5]]

Along none axis : 
 [ 1  5 10 14]
