<a href="https://colab.research.google.com/github/dha3sh/LetsUpgrade-Python-Data-Science-assignments/blob/main/np_sort_and_np_where3d_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

a = np.array([[5, 14], [10, 1]])
arr1 = np.sort(a, axis = 0)		
print ("Along first axis : \n", arr1)		



a = np.array([[10, 14], [5, 1]])
arr2 = np.sort(a, axis = -1)		
print ("\nAlong first axis : \n", arr2)


a = np.array([[5, 14], [10, 1]])
arr1 = np.sort(a, axis = None)		
print ("\nAlong none axis : \n", arr1)


Along first axis : 
 [[ 5  1]
 [10 14]]

Along first axis : 
 [[10 14]
 [ 1  5]]

Along none axis : 
 [ 1  5 10 14]


In [5]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])

print(a)

print ('Indices of elements <4')

b = np.where(a<4)
print(b)

print("Elements which are <4")
print(a[b])


[[1 2 3]
 [4 5 6]]
Indices of elements <4
(array([0, 0, 0]), array([0, 1, 2]))
Elements which are <4
[1 2 3]
